# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlVNoITnXcMTrzCCWcmjAt0Y_mjIddq3
"""

# Importing Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Load the Dataset
# Download the dataset from UCI ML Repository or use a custom dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip"
student_data = pd.read_csv("student-mat.csv", sep=";")  # For simplicity, using only math data

# Step 2: Preprocessing
# Selecting relevant features and target (G3 = final grade)
features = ["G1", "G2", "studytime", "failures", "absences"]
target = "G3"
X = student_data[features]
y = student_data[target]

# Step 3: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Train the Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Step 5: Make Predictions
y_pred = model.predict(X_test)

# Step 6: Evaluate the Model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

# Step 7: Visualize Results
# Scatter plot of actual vs predicted grades
plt.figure(figsize=(8, 6))
sns.scatterplot(x=y_test, y=y_pred)
plt.xlabel("Actual Grades")
plt.ylabel("Predicted Grades")
plt.title("Actual vs Predicted Grades")
plt.show()

# Step 8: Feature Importance
importance = model.feature_importances_
feature_names = features
plt.figure(figsize=(8, 6))
sns.barplot(x=importance, y=feature_names)
plt.xlabel("Feature Importance")
plt.ylabel("Features")
plt.title("Feature Importance in Predicting Student Performance")
plt.show()

from google.colab import drive
drive.mount('/content/drive')