# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vglev00RMLhCOzxDhic4J6Rw8Z34OwsR
"""

# Importing Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Step 1: Create a dataset or load one
data = {
    'Size (sq ft)': [850, 900, 1200, 1500, 2000, 2500],
    'Bedrooms': [2, 2, 3, 3, 4, 5],
    'Location Index': [1, 1, 2, 2, 3, 3],  # Categorical data converted to numerical
    'Price (in 1000s)': [150, 160, 240, 300, 400, 500]
}
df = pd.DataFrame(data)

# Step 2: Prepare features and target
X = df[['Size (sq ft)', 'Bedrooms', 'Location Index']]
y = df['Price (in 1000s)']

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Train a Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 5: Make predictions
y_pred = model.predict(X_test)

# Step 6: Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

# Optional: Predict for a new house
new_house = [[1800, 3, 2]]  # Size, Bedrooms, Location Index
predicted_price = model.predict(new_house)
print(f"Predicted Price for new house: {predicted_price[0]} (in 1000s)")



# Importing Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Step 1: Load the dataset
# Sample dataset
data = {
    'Review': [
        'The movie was fantastic!',
        'I hated the plot of the film.',
        'Amazing performances by the actors.',
        'Terrible direction and weak story.',
        'A must-watch for everyone!',
        'Not worth the time.'
    ],
    'Sentiment': ['Positive', 'Negative', 'Positive', 'Negative', 'Positive', 'Negative']
}
df = pd.DataFrame(data)

# Step 2: Preprocess the data
X = df['Review']
y = df['Sentiment']

# Convert text into a bag-of-words representation
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X)

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 4: Train a Naive Bayes model
model = MultinomialNB()
model.fit(X_train, y_train)

# Step 5: Make predictions
y_pred = model.predict(X_test)

# Step 6: Evaluate the model
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Step 7: Test with new reviews
new_reviews = ['The movie was amazing!', 'It was a total waste of time.']
new_reviews_vectorized = vectorizer.transform(new_reviews)
predictions = model.predict(new_reviews_vectorized)
print("New Predictions:", predictions)

